# DISTRIBUIÇÃO DE FREQUÊNCIAS

# 0.0 Importações

In [1]:
library(dplyr)
library(sampling)
library(TeachingSampling)

Attaching package: 'dplyr'

The following objects are masked from 'package:stats':

    filter, lag

The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union

Warning message:
"package 'sampling' was built under R version 3.6.3"

In [2]:
enem2019_tratado <- read.csv('enem2019_tratado.csv', sep=',')

In [3]:
head(enem2019_tratado)

   NU_INSCRICAO NO_MUNICIPIO_RESIDENCIA NU_IDADE TP_SEXO TP_COR_RACA
1  190001017053 Santa Isabel            22       M       3
3  190001019850 São Paulo               17       F       3
4  190001024874 São Bernardo do Campo   19       M       3
6  190001031050 Embu-Guaçu              17       F       3
9  190001045429 Guarulhos               23       F       1
11 190001050482 São José do Rio Preto   18       F       1
   TP_NACIONALIDADE TP_ESCOLA TP_ENSINO CO_ESCOLA TP_PRESENCA_CN ... NOTA_LC
1  1                1          1              NA  1              ... 592.9
3  1                3          1        15567761  1              ... 634.3
4  1                2          1        35904958  1              ... 509.6
6  1                2          1              NA  1              ... 487.2
9  1                1         NA              NA  1              ... 629.3
11 1                2          1        35028927  1              ... 555.9
   NOTA_MT TP_LINGUA TP_STATUS_REDACAO NOTA_COMP1 NOTA_COMP2 NOTA_COMP3
1  600.2   0         1                 160        200        180
3  731.8   0         1                 160        120        200
4  393.2   1         1                  80        160        120
6  419.2   0         1                 120        120        120
9  796.1   0         1                 160        200        180
11 612.8   1         1                 120        160        120
   NOTA_COMP4 NOTA_COMP5 NOTA_REDACAO
1  200        200        940
3  200        200        880
4  100        100        560
6  120         80        560
9  180        160        880
11  80        100        580

In [4]:
enem_sorocaba <- enem2019_tratado %>% filter(NO_MUNICIPIO_RESIDENCIA=='Sorocaba')

# 1.0 Tabela de frequências absolutas

In [5]:
freq_abs <- table(enem_sorocaba$NU_IDADE)
freq_abs_df <- data.frame(freq_abs)
freq_abs_df[order(freq_abs_df$Freq, decreasing = TRUE), ]

   Var1 Freq
4  17   2993
5  18   1558
6  19    872
7  20    556
8  21    372
9  22    279
10 23    206
11 24    154
12 25    114
13 26    105
15 28     87
14 27     76
16 29     72
17 30     52
19 32     50
21 34     42
22 35     42
20 33     41
18 31     40
23 36     37
25 38     29
26 39     29
24 37     26
27 40     23
29 42     23
30 43     21
28 41     20
33 46     18
35 48     15
31 44     14
32 45     14
41 54     13
36 49     11
38 51     11
39 52      9
40 53      9
3  16      8
34 47      8
37 50      7
48 61      6
43 56      4
47 60      4
2  15      3
42 55      2
44 57      2
45 58      2
46 59      2
50 64      2
1  14      1
49 62      1
51 65      1
52 70      1
53 73      1

# 2.0 Frequência relativa

In [6]:
freq_rel <- prop.table(freq_abs)
freq_rel_df <- data.frame(freq_rel)
freq_rel_df[order(freq_rel_df$Freq, decreasing = TRUE),]

   Var1 Freq
4  17   0.3700544016
5  18   0.1926310584
6  19   0.1078140455
7  20   0.0687438180
8  21   0.0459940653
9  22   0.0344955490
10 23   0.0254698318
11 24   0.0190405539
12 25   0.0140949555
13 26   0.0129821958
15 28   0.0107566766
14 27   0.0093966370
16 29   0.0089020772
17 30   0.0064292779
19 32   0.0061819980
21 34   0.0051928783
22 35   0.0051928783
20 33   0.0050692384
18 31   0.0049455984
23 36   0.0045746785
25 38   0.0035855589
26 39   0.0035855589
24 37   0.0032146390
27 40   0.0028437191
29 42   0.0028437191
30 43   0.0025964392
28 41   0.0024727992
33 46   0.0022255193
35 48   0.0018545994
31 44   0.0017309594
32 45   0.0017309594
41 54   0.0016073195
36 49   0.0013600396
38 51   0.0013600396
39 52   0.0011127596
40 53   0.0011127596
3  16   0.0009891197
34 47   0.0009891197
37 50   0.0008654797
48 61   0.0007418398
43 56   0.0004945598
47 60   0.0004945598
2  15   0.0003709199
42 55   0.0002472799
44 57   0.0002472799
45 58   0.0002472799
46 59   0.0002472799
50 64   0.0002472799
1  14   0.0001236400
49 62   0.0001236400
51 65   0.0001236400
52 70   0.0001236400
53 73   0.0001236400

# 3.0 Porcentagem da frequência relativa

In [7]:
p_freq_rel <- 100 * prop.table(freq_rel)
p_freq_rel

         14          15          16          17          18          19
 0.01236400  0.03709199  0.09891197 37.00544016 19.26310584 10.78140455
         20          21          22          23          24          25
 6.87438180  4.59940653  3.44955490  2.54698318  1.90405539  1.40949555
         26          27          28          29          30          31
 1.29821958  0.93966370  1.07566766  0.89020772  0.64292779  0.49455984
         32          33          34          35          36          37
 0.61819980  0.50692384  0.51928783  0.51928783  0.45746785  0.32146390
         38          39          40          41          42          43
 0.35855589  0.35855589  0.28437191  0.24727992  0.28437191  0.25964392
         44          45          46          47          48          49
 0.17309594  0.17309594  0.22255193  0.09891197  0.18545994  0.13600396
         50          51          52          53          54          55
 0.08654797  0.13600396  0.11127596  0.11127596  0.16073195  0.02472799
         56          57          58          59          60          61
 0.04945598  0.02472799  0.02472799  0.02472799  0.04945598  0.07418398
         62          64          65          70          73
 0.01236400  0.02472799  0.01236400  0.01236400  0.01236400

# 4.0 Criar uma linha com o total

In [8]:
freq_abs <- c(freq_abs, sum(freq_abs))
names(freq_abs)[54] <- "Total"
freq_abs

   14    15    16    17    18    19    20    21    22    23    24    25    26
    1     3     8  2993  1558   872   556   372   279   206   154   114   105
   27    28    29    30    31    32    33    34    35    36    37    38    39
   76    87    72    52    40    50    41    42    42    37    26    29    29
   40    41    42    43    44    45    46    47    48    49    50    51    52
   23    20    23    21    14    14    18     8    15    11     7    11     9
   53    54    55    56    57    58    59    60    61    62    64    65    70
    9    13     2     4     2     2     2     4     6     1     2     1     1
   73 Total
    1  8088

# 5.0 Juntando a frequência relativa e a frequência percentual

In [9]:
freq_rel <- c(freq_rel,sum(freq_rel))

In [11]:
p_freq_rel <- c(p_freq_rel, sum(p_freq_rel))

In [12]:
# tabela final com todos os valores

tabela_final <- cbind(freq_abs,
                     freq_rel = round(freq_rel, digits=5),
                     p_freq_rel = round(p_freq_rel, digits=2))

In [13]:
tabela_final

      freq_abs freq_rel p_freq_rel
14       1     0.00012    0.01
15       3     0.00037    0.04
16       8     0.00099    0.10
17    2993     0.37005   37.01
18    1558     0.19263   19.26
19     872     0.10781   10.78
20     556     0.06874    6.87
21     372     0.04599    4.60
22     279     0.03450    3.45
23     206     0.02547    2.55
24     154     0.01904    1.90
25     114     0.01409    1.41
26     105     0.01298    1.30
27      76     0.00940    0.94
28      87     0.01076    1.08
29      72     0.00890    0.89
30      52     0.00643    0.64
31      40     0.00495    0.49
32      50     0.00618    0.62
33      41     0.00507    0.51
34      42     0.00519    0.52
35      42     0.00519    0.52
36      37     0.00457    0.46
37      26     0.00321    0.32
38      29     0.00359    0.36
39      29     0.00359    0.36
40      23     0.00284    0.28
41      20     0.00247    0.25
42      23     0.00284    0.28
43      21     0.00260    0.26
44      14     0.00173    0.17
45      14     0.00173    0.17
46      18     0.00223    0.22
47       8     0.00099    0.10
48      15     0.00185    0.19
49      11     0.00136    0.14
50       7     0.00087    0.09
51      11     0.00136    0.14
52       9     0.00111    0.11
53       9     0.00111    0.11
54      13     0.00161    0.16
55       2     0.00025    0.02
56       4     0.00049    0.05
57       2     0.00025    0.02
58       2     0.00025    0.02
59       2     0.00025    0.02
60       4     0.00049    0.05
61       6     0.00074    0.07
62       1     0.00012    0.01
64       2     0.00025    0.02
65       1     0.00012    0.01
70       1     0.00012    0.01
73       1     0.00012    0.01
Total 8088     1.00000  100.00

# 6.0 Construindo classes de frequências

In [15]:
intervalo_classes <- seq(10,75,5)
intervalo_classes

 [1] 10 15 20 25 30 35 40 45 50 55 60 65 70 75

In [16]:
tabela_classes <- table(cut(enem_sorocaba$NU_IDADE, breaks=intervalo_classes, right=FALSE))

In [18]:
tabela_classes <- data.frame(tabela_classes)
tabela_classes

   Var1    Freq
1  [10,15)    1
2  [15,20) 5434
3  [20,25) 1567
4  [25,30)  454
5  [30,35)  225
6  [35,40)  163
7  [40,45)  101
8  [45,50)   66
9  [50,55)   49
10 [55,60)   12
11 [60,65)   13
12 [65,70)    1
13 [70,75)    2